### PR TITLE
Patch for new Anki Versions

### LINKED ISSUE #22: Cannot Launch Anki with the Add-On
Below is the error paste
```
Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeat until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 6.3.1 PyQt 6.3.1
Platform: Windows 10
Flags: frz=True ao=True sv=?
Add-ons, last update check: 2022-07-21 23:05:47

Caught exception:
Traceback (most recent call last):
  File "aqt.progress", line 118, in handler
  File "aqt.main", line 197, in on_window_init
  File "aqt.main", line 243, in setupProfileAfterWebviewsLoaded
  File "aqt.main", line 288, in setupProfile
  File "aqt.main", line 294, in showProfileManager
  File "aqt.main", line 676, in moveToState
  File "aqt.hooks_gen", line 3797, in __call__
  File "anki.hooks", line 34, in runHook
  File "C:\Users\JasonBaby\AppData\Roaming\Anki2\addons21\1133851639\__init__.py", line 95, in onState
    dueToday()
  File "C:\Users\JasonBaby\AppData\Roaming\Anki2\addons21\1133851639\__init__.py", line 67, in dueToday
    for i in mw.col.sched.deckDueTree():
AttributeError: 'NoneType' object has no attribute 'sched'
```

### PR DESCRIPTION
**Pull request by NetherStar64**
Fixes #22
You should test this on other versions, it just worked for me this way.
Also, I only updated the one problematic hook, the others should maybe also be converted from legacy.

### CODE REVIEW

**Comment by subtra3t** [comment]
Does this work with the latest version of Anki (2.1.6x)?

**Comment by Monacraft** [comment]
With the latest update the code should work with all versions of Anki 2.1
